### ISSUE TITLE
attend to uncaught promise error in configuration.ts

### ISSUE THREAD

**Issue by rpruim** [senior-knights/course-schedulizer#319]
When I have the console open, I often see something like this when launching the app

```
Uncaught (in promise) Error: Error: your settings are undefined. Try reloading the page. If this error persists, try the troubleshooting guide: https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md
    at getConfForUrl (configuration.ts:163:15)
    at getConf (configuration.ts:149:12)
    at content.ts:299:51
```

**Comment by VelSharon** [comment]
How did you launch the app? I ran it on my development server, and I don't see this error on the console. I also ran the actual webapp and checked the console, but this is not the error that shows up. Could you please provide the steps to reproduce this issue? 

![Screenshot](https://user-images.githubusercontent.com/90476681/218280989-2137ece4-002d-49d3-b25e-20229e0ace06.png)

**Comment by rpruim** [comment]
I'm getting this in Chrome today when I load the attached csv.

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/722231/218513895-6151f9b6-905e-4211-ae1d-463ebc0b33a0.png">

[MathStat-2022-23-current.csv](https://github.com/senior-knights/course-schedulizer/files/10724133/MathStat-2022-23-current.csv)
